[tools]
node = "24.12.0"

[tasks.up]
run = "docker compose up -d"

[tasks.down]
run = "docker compose down"

[tasks.dev]
run = "npm run dev"

[tasks.migrate]
run = "./node_modules/.bin/prisma migrate dev"

[env]
PORT = "3000"
